services:
  decidim-better_surveys:
    entrypoint: ""
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.27
    privileged: true
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@better-surveys-pg:5432/decidim
      - DEV_MODULE=decidim-better_surveys
      - DEV_GEMFILE=/home/decidim/module/contrib/Gemfile.dev
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - better-surveys-pg

  better-surveys-pg:
    image: postgres:15
    volumes:
      - better_surveys_pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  better_surveys_pg-data: {}
